### ISSUE TITLE
Question About _maybe_mask

### ISSUE THREAD

**Issue by shawnxu1318** [facebookresearch/higher#17]
Hi Dear Author,
      I am wondering when and why we need to apply a gradient mask to parameters equal to 0?
`                mask = exp_avg_sq == 0.
                _maybe_mask(exp_avg_sq, mask)
`

**Comment by egrefen** [comment]
The derivative of the square root is undefined at 0, which is the starting value of exp_avg_sq, which we don't want to backpropagate through anyway since it typically only holds for the very first step of an unrolled loop. To avoid proliferation of Nan's, we zero this component, which may seem like a mathematical abomination (it is) but it's for a part of the backward graph which doesn't matter.
