### ISSUE TITLE
Is DataParallel supported?

### ISSUE THREAD

**Issue by csyanbin** [facebookresearch/higher#24]
Hi, Thanks for this great repo of higher gradient computation and backpropagation.

Since many steps + higher-order gradient may occupy huge gpu memory, I am wondering if multiple-gpu training such as DataParallel supported by this repo?

**Comment by egrefen** [comment]
That's a good question: I haven't had the need to use DataParallel in my own research, so haven't looked into this. Have you tried using it? If not, could you, and get back to me with details of what goes wrong (if anything)?

**Comment by csyanbin** [comment]
I simply wrap my maml model with torch.nn.DataParallel and got the following error:

```
Traceback (most recent call last):
  File "train_mini_bn_wMul.py", line 268, in <module>
    main()
  File "train_mini_bn_wMul.py", line 142, in main
    spt_logits = fnet(x_spt[i]) # i is the i-the task
  File "/mnt/yanbin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/yanbin/anaconda3/lib/python3.7/site-packages/higher/patch.py", line 349, in _patched_forward
    return self.boxed_forward(*args, **kwargs)
  File "/mnt/yanbin/anaconda3/lib/python3.7/site-packages/higher/patch.py", line 290, in patched_forward
    return true_forward(self, *args, **kwargs)
  File "/mnt/yanbin/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/mnt/yanbin/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 156, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/mnt/yanbin/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 162, in replicate
    param_idx = param_indices[param]
KeyError: tensor([[[[ 0.0992, -0.0849, -0.0373],
```

**Comment by egrefen** [comment]
Hello @csyanbin. I've talked to @albanD from the pytorch team about this. It sounds like the implementation of DataParallel involves a lot of copying over models, in a way which prevents us from tracking the combined meta-gradient history and/or is not compatible with the monkey-patching we do to enable backpropagating through the optimization loop.

Based on my limited understanding, it sounds like a lot of the DataParallel logic would need to be changed to support this, so the only way I can see that happening is if parts of this framework are one day subsumed by features of core pytorch.

In the meantime, note that you can provide `device` info to several high level functions in `higher`, which enables you to do the meta-learning on CPU while doing your main loop on GPU. Not much help if you're doing MAML, but better than nothing for many other applications...

I'm closing this issue for the moment, as we are unable to support a resolution.

**Comment by RafaelPoyiadzi** [comment]
Hi, (and thanks for the library)

Is higher not supposed to be working with DistributedDataParallel as well? Because I got the code to run (without any errors) but I am wondering whether it is doing what it is supposed to be doing.

My current understanding is that inside the higher.innerloop_ctx the ddp synchronisation is not happening (again my understanding is that it is supposed to be triggered with .backward(), that is happening inside diffopt.step(inner_loss)), but it happens right after the context manager.
--> synchronisation seems to be happening only at the outer level.

Could provide pieces of code if necessary.

Pseudo-code:
with (model_ddp, inner_optimizer, device=local_rank_device) as (fmodel, diffopt):
--inner_loss = ...
--diffopt.step(inner_loss)
--outer_loss = ...
--// fmodel.weights on cuda:0 != fmodel.weights on cuda:1
outer_loss.backward()
// model_ddp.weights on cuda:0 == model_ddp.weights on cuda:1

Thanks! 
Rafael
