### ISSUE TITLE
Only need first and last params/gradients

### ISSUE THREAD

**Issue by renesax14** [facebookresearch/higher#31]
I saw the warning:

> Beware that when unrolling your optimisation like this for k, all gradients and all activations of your model at each step is kept in memory, meaning the memory footprint of your model is k times greater.

but I do NOT want all of them. I only want the current and first. Anything else can be thrown away and NOT stored. How can I achieve that?

**Comment by egrefen** [comment]
You need to compute and keep in memory the intermediate steps for the backward pass to be possible, much like you need to compute and retain the intermediate activations of an RNN in order to backpropagate loss from the final state to the first state. The intermediate states will be garbage collected after the (meta-)backward pass anyways, but the `O(n)` space complexity in the length `n` of the unrolled inner loop is inherent to all such gradient-based meta-learning methods.

Closing the issue, but please re-open and comment if this doesn't clarify things.
