### ISSUE TITLE
Questions about meaning of fast weights.

### ISSUE THREAD

**Issue by briankosw** [facebookresearch/higher#46]
What exactly does it mean  by *fast weights*? It is mentioned quite often throughout the documentation, but it is never explained.

**Comment by egrefen** [comment]
Fast weights is term which as historically been used throughout the meta-learning literature, starting perhaps with this paper
```bibtex
@article{schmidhuber1992learning,
  title={Learning to control fast-weight memories: An alternative to dynamic recurrent networks},
  author={Schmidhuber, J{\"u}rgen},
  journal={Neural Computation},
  volume={4},
  number={1},
  pages={131--139},
  year={1992},
  publisher={MIT Press}
}
```

We refer to the weights in the unrolled model as "fast" because we do many "quick" unrolls (where speed here refers more to the number of updates done relative to the meta weights) in order to do fewer "slow" weight updates of our meta-weights.

I agree the nomenclature is not super clear, and when we do a doc refresh we'll try to use less of these idiosyncratic historical terms.

**Comment by brando90** [comment]
> Fast weights is term which as historically been used throughout the meta-learning literature, starting perhaps with this paper
> 
> ```
> @article{schmidhuber1992learning,
>   title={Learning to control fast-weight memories: An alternative to dynamic recurrent networks},
>   author={Schmidhuber, J{\"u}rgen},
>   journal={Neural Computation},
>   volume={4},
>   number={1},
>   pages={131--139},
>   year={1992},
>   publisher={MIT Press}
> }
> ```
> 
> We refer to the weights in the unrolled model as "fast" because we do many "quick" unrolls (where speed here refers more to the number of updates done relative to the meta weights) in order to do fewer "slow" weight updates of our meta-weights.
> 
> I agree the nomenclature is not super clear, and when we do a doc refresh we'll try to use less of these idiosyncratic historical terms.

for example in the case of MAML, is fast weights the term used for the weights at the end of a few steps of adaptation? @egrefen
