### ISSUE TITLE
Meaning of stop-gradient

### ISSUE THREAD

**Issue by JonMuehlst** [facebookresearch/higher#56]
Could you please elaborate on what the "stop-gradient" operator does?

**Comment by egrefen** [comment]
Could please clarify what stop-gradient operator this is referring to? There is no such operator in the codebase.

**Comment by JonMuehlst** [comment]
I'd like to be sure I understand the algorithm 'higher' is based on such that I don't use it as a black box. I assume that the stop-gradient operator mentioned in your paper "Generalized Inner Loop Meta Learning" is important for the dynamic programming implementation of the unrolling yet it's not clear to me how it works.

**Comment by egrefen** [comment]
In the loop cover lines 10-17 of the paper, we step backwards through the forward graph, computing the partial derivatives of the meta-loss with regard to the meta-parameters as used at that each time step. The stop-grad is there to indicate we are taking the "local" partial derivative, rather than the partial derivative with regard to earlier steps in the unrolled loop. As you say, it's just a way of spelling out the dynamic programming algorithm.

**Comment by JonMuehlst** [comment]
Thank you very much for the detailed explanation!
